from . import base
from typing import Any

class AdaBound(base.Optimizer):
    base_lr: Any = ...
    final_lr: Any = ...
    beta_1: Any = ...
    beta_2: Any = ...
    eps: Any = ...
    gamma: Any = ...
    m: Any = ...
    v: Any = ...
    def __init__(self, lr: float = ..., beta_1: float = ..., beta_2: float = ..., eps: float = ..., gamma: float = ..., final_lr: float = ...) -> None: ...
