from . import base
from typing import Any

class AdaMax(base.Optimizer):
    beta_1: Any = ...
    beta_2: Any = ...
    eps: Any = ...
    m: Any = ...
    u: Any = ...
    def __init__(self, lr: float = ..., beta_1: float = ..., beta_2: float = ..., eps: float = ...) -> None: ...
