from . import base
from typing import Any

class AdaDelta(base.Optimizer):
    rho: Any = ...
    eps: Any = ...
    g2: Any = ...
    s2: Any = ...
    def __init__(self, rho: float = ..., eps: float = ...) -> None: ...
