import typing
from . import base, schedulers
from typing import Any

class AMSGrad(base.Optimizer):
    beta_1: Any = ...
    beta_2: Any = ...
    eps: Any = ...
    correct_bias: Any = ...
    m: Any = ...
    v: Any = ...
    v_hat: Any = ...
    def __init__(self, lr: typing.Union[float, schedulers.Scheduler]=..., beta_1: Any=..., beta_2: Any=..., eps: Any=..., correct_bias: Any=...) -> None: ...
