from . import base as base
from typing import Any

class Averager(base.Optimizer):
    optimizer: Any = ...
    start: Any = ...
    avg_w: Any = ...
    n_iterations: int = ...
    def __init__(self, optimizer: base.Optimizer, start: int=...) -> None: ...
    def update_before_pred(self, w: Any): ...
