from . import base
from typing import Any

class FTRLProximal(base.Optimizer):
    alpha: Any = ...
    beta: Any = ...
    l1: Any = ...
    l2: Any = ...
    z: Any = ...
    n: Any = ...
    n_iterations: int = ...
    def __init__(self, alpha: float = ..., beta: float = ..., l1: float = ..., l2: float = ...) -> None: ...
