from . import base
from typing import Any

class NesterovMomentum(base.Optimizer):
    rho: Any = ...
    s: Any = ...
    def __init__(self, lr: float = ..., rho: float = ...) -> None: ...
    def update_before_pred(self, w: Any): ...
