from . import base
from typing import Any

class RMSProp(base.Optimizer):
    rho: Any = ...
    eps: Any = ...
    g2: Any = ...
    def __init__(self, lr: float = ..., rho: float = ..., eps: float = ...) -> None: ...
