from river import base as base
from typing import Any, Optional

class RBFSampler(base.Transformer):
    gamma: Any = ...
    n_components: Any = ...
    seed: Any = ...
    rng: Any = ...
    weights: Any = ...
    offsets: Any = ...
    def __init__(self, gamma: Any=..., n_components: Any=..., seed: int=...) -> None: ...
    def transform_one(self, x: Any, y: Optional[Any] = ...): ...
