from river import base
from typing import Any

class PolynomialExtender(base.Transformer):
    degree: Any = ...
    interaction_only: Any = ...
    include_bias: Any = ...
    bias_name: Any = ...
    def __init__(self, degree: int = ..., interaction_only: bool = ..., include_bias: bool = ..., bias_name: str = ...) -> None: ...
    def transform_one(self, x: Any): ...
