from river import base
from typing import Any

class KMeans(base.Clusterer):
    n_clusters: Any = ...
    halflife: Any = ...
    mu: Any = ...
    sigma: Any = ...
    p: Any = ...
    seed: Any = ...
    centers: Any = ...
    def __init__(self, n_clusters: Any=..., halflife: Any=..., mu: Any=..., sigma: Any=..., p: Any=..., seed: int=...) -> None: ...
    def learn_predict_one(self, x: Any): ...
    def learn_one(self, x: Any): ...
    def predict_one(self, x: Any): ...
