from .extremely_fast_decision_tree import ExtremelyFastDecisionTreeClassifier as ExtremelyFastDecisionTreeClassifier
from .hoeffding_adaptive_tree_classifier import HoeffdingAdaptiveTreeClassifier as HoeffdingAdaptiveTreeClassifier
from .hoeffding_adaptive_tree_regressor import HoeffdingAdaptiveTreeRegressor as HoeffdingAdaptiveTreeRegressor
from .hoeffding_tree_classifier import HoeffdingTreeClassifier as HoeffdingTreeClassifier
from .hoeffding_tree_regressor import HoeffdingTreeRegressor as HoeffdingTreeRegressor
from .isoup_tree_regressor import iSOUPTreeRegressor as iSOUPTreeRegressor
from .label_combination_hoeffding_tree import LabelCombinationHoeffdingTreeClassifier as LabelCombinationHoeffdingTreeClassifier
