from river import base as base, tree as tree
from river.utils.skmultiflow_utils import normalize_values_in_dict as normalize_values_in_dict
from typing import Any

class LabelCombinationHoeffdingTreeClassifier(tree.HoeffdingTreeClassifier, base.MultiOutputMixin):
    def __init__(self, grace_period: int=..., max_depth: int=..., split_criterion: str=..., split_confidence: float=..., tie_threshold: float=..., leaf_prediction: str=..., nb_threshold: int=..., nominal_attributes: list=..., attr_obs: str=..., attr_obs_params: dict=..., **kwargs: Any) -> None: ...
    def learn_one(self, x: Any, y: Any, *, sample_weight: float = ...): ...
    def predict_proba_one(self, x: Any): ...
    def predict_one(self, x: Any): ...
