from river.base import DriftDetector as DriftDetector
from typing import Any

class DDM(DriftDetector):
    sample_count: Any = ...
    miss_prob: Any = ...
    miss_std: Any = ...
    miss_prob_sd_min: Any = ...
    miss_prob_min: Any = ...
    miss_sd_min: Any = ...
    min_num_instances: Any = ...
    warning_level: Any = ...
    out_control_level: Any = ...
    estimation: Any = ...
    delay: Any = ...
    def __init__(self, min_num_instances: int = ..., warning_level: float = ..., out_control_level: float = ...) -> None: ...
    def reset(self) -> None: ...
    def update(self, value: Any): ...
