from river.base import DriftDetector as DriftDetector
from typing import Any

class EDDM(DriftDetector):
    FDDM_OUTCONTROL: float = ...
    FDDM_WARNING: float = ...
    FDDM_MIN_NUM_INSTANCES: int = ...
    m_num_errors: Any = ...
    m_min_num_errors: int = ...
    m_n: Any = ...
    m_d: Any = ...
    m_lastd: Any = ...
    m_mean: Any = ...
    m_std_temp: Any = ...
    m_m2s_max: Any = ...
    m_last_level: Any = ...
    estimation: Any = ...
    delay: Any = ...
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def update(self, value: Any) -> tuple: ...
