from river.base import DriftDetector as DriftDetector
from typing import Any

class HDDM_A(DriftDetector):
    n_min: int = ...
    c_min: int = ...
    total_n: int = ...
    total_c: int = ...
    n_max: int = ...
    c_max: int = ...
    n_estimation: int = ...
    c_estimation: int = ...
    estimation: Any = ...
    delay: Any = ...
    drift_confidence: Any = ...
    warning_confidence: Any = ...
    two_sided_test: Any = ...
    def __init__(self, drift_confidence: float = ..., warning_confidence: float = ..., two_sided_test: bool = ...) -> None: ...
    def update(self, value: Any) -> tuple: ...
    def reset(self) -> None: ...
