from river.base import DriftDetector as DriftDetector
from typing import Any

class HDDM_W(DriftDetector):
    class SampleInfo:
        EWMA_estimator: Any = ...
        independent_bounded_condition_sum: float = ...
        def __init__(self) -> None: ...
    total: Any = ...
    sample1_decr_monitor: Any = ...
    sample1_incr_monitor: Any = ...
    sample2_decr_monitor: Any = ...
    sample2_incr_monitor: Any = ...
    incr_cutpoint: Any = ...
    decr_cutpoint: Any = ...
    width: int = ...
    delay: int = ...
    drift_confidence: Any = ...
    warning_confidence: Any = ...
    lambda_option: Any = ...
    two_sided_test: Any = ...
    estimation: Any = ...
    def __init__(self, drift_confidence: float = ..., warning_confidence: float = ..., lambda_option: float = ..., two_sided_test: bool = ...) -> None: ...
    def update(self, value: Any): ...
    def reset(self) -> None: ...
