from river.base import DriftDetector as DriftDetector
from typing import Any, Optional

class KSWIN(DriftDetector):
    window_size: Any = ...
    stat_size: Any = ...
    alpha: Any = ...
    p_value: int = ...
    n: int = ...
    window: Any = ...
    def __init__(self, alpha: float = ..., window_size: int = ..., stat_size: int = ..., window: Optional[Any] = ...) -> None: ...
    def update(self, value: Any) -> tuple: ...
    def reset(self) -> None: ...
