from river.base import DriftDetector as DriftDetector
from typing import Any

class PageHinkley(DriftDetector):
    min_instances: Any = ...
    delta: Any = ...
    threshold: Any = ...
    alpha: Any = ...
    x_mean: Any = ...
    sample_count: Any = ...
    sum: Any = ...
    def __init__(self, min_instances: int = ..., delta: float = ..., threshold: int = ..., alpha: Any = ...) -> None: ...
    def reset(self) -> None: ...
    def update(self, value: Any) -> tuple: ...
