import abc
import numbers
import typing
from . import base as base
from typing import Any

class DriftDetector(base.Base, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    @property
    def change_detected(self) -> bool: ...
    @property
    def warning_detected(self) -> bool: ...
    @abc.abstractmethod
    def update(self, value: numbers.Number) -> typing.Tuple[bool, bool]: ...
    def __iadd__(self, other: Any) -> None: ...
