from typing import Any

class EnsembleMixin:
    models: Any = ...
    def __init__(self, models: Any) -> None: ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, index: Any): ...
