from .._attribute_test import AttributeSplitSuggestion as AttributeSplitSuggestion, NominalAttributeBinaryTest as NominalAttributeBinaryTest, NominalAttributeMultiwayTest as NominalAttributeMultiwayTest
from .attribute_observer import AttributeObserver as AttributeObserver
from river.stats import Var as Var
from river.utils import VectorDict as VectorDict
from typing import Any

class NominalAttributeRegressionObserver(AttributeObserver):
    def __init__(self) -> None: ...
    def update(self, att_val: Any, target: Any, sample_weight: float = ...): ...
    def probability_of_attribute_value_given_class(self, att_val: Any, target: Any) -> None: ...
    def best_evaluated_split_suggestion(self, criterion: Any, pre_split_dist: Any, att_idx: Any, binary_only: Any): ...
