from .._attribute_test import AttributeSplitSuggestion as AttributeSplitSuggestion, NominalAttributeBinaryTest as NominalAttributeBinaryTest, NominalAttributeMultiwayTest as NominalAttributeMultiwayTest
from .attribute_observer import AttributeObserver as AttributeObserver
from typing import Any

class NominalAttributeClassObserver(AttributeObserver):
    def __init__(self) -> None: ...
    def update(self, att_val: Any, class_val: Any, sample_weight: Any): ...
    def probability_of_attribute_value_given_class(self, att_val: Any, class_val: Any): ...
    def best_evaluated_split_suggestion(self, criterion: Any, pre_split_dist: Any, att_idx: Any, binary_only: Any): ...
    def class_dist_from_multiway_split(self): ...
    def class_dist_from_binary_split(self, val_idx: Any): ...
