from .._attribute_test import AttributeSplitSuggestion as AttributeSplitSuggestion, NumericAttributeBinaryTest as NumericAttributeBinaryTest
from .attribute_observer import AttributeObserver as AttributeObserver
from river.base.typing import ClfTarget as ClfTarget
from river.proba import Gaussian as Gaussian
from typing import Any

class NumericAttributeClassObserverGaussian(AttributeObserver):
    n_splits: Any = ...
    def __init__(self, n_splits: int=...) -> None: ...
    def update(self, att_val: Any, class_val: Any, sample_weight: Any): ...
    def probability_of_attribute_value_given_class(self, att_val: Any, class_val: Any): ...
    def best_evaluated_split_suggestion(self, criterion: Any, pre_split_dist: Any, att_idx: Any, binary_only: Any): ...
