from . import base
from river import optim
from typing import Any

class Baseline(base.Recommender):
    optimizer: Any = ...
    u_optimizer: Any = ...
    i_optimizer: Any = ...
    loss: Any = ...
    l2: Any = ...
    initializer: Any = ...
    clip_gradient: Any = ...
    global_mean: Any = ...
    u_biases: Any = ...
    i_biases: Any = ...
    def __init__(self, optimizer: optim.Optimizer=..., loss: optim.losses.Loss=..., l2: Any=..., initializer: optim.initializers.Initializer=..., clip_gradient: Any=...) -> None: ...
