from . import base
from river import optim
from typing import Any

class FunkMF(base.Recommender):
    n_factors: Any = ...
    u_optimizer: Any = ...
    i_optimizer: Any = ...
    loss: Any = ...
    l2: Any = ...
    initializer: Any = ...
    clip_gradient: Any = ...
    seed: Any = ...
    u_latents: Any = ...
    i_latents: Any = ...
    def __init__(self, n_factors: Any=..., optimizer: optim.Optimizer=..., loss: optim.losses.Loss=..., l2: Any=..., initializer: optim.initializers.Initializer=..., clip_gradient: Any=..., seed: int=...) -> None: ...
