from . import base
from typing import Any, Optional

class RandomNormal(base.Recommender):
    variance: Any = ...
    mean: Any = ...
    seed: Any = ...
    def __init__(self, seed: Optional[Any] = ...) -> None: ...
