import surprise
from . import base as base
from typing import Any

class SurpriseWrapper(surprise.AlgoBase):
    river_recommender: Any = ...
    def __init__(self, river_recommender: base.Recommender) -> None: ...
    def fit(self, trainset: Any): ...
    def estimate(self, user: Any, item: Any): ...
