import collections
from typing import Any

class Bin:
    left: Any = ...
    right: Any = ...
    count: Any = ...
    def __init__(self, left: Any, right: Any, count: Any) -> None: ...
    def __iadd__(self, other: Any): ...
    def __lt__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...

class Histogram(collections.UserList):
    max_bins: Any = ...
    n: int = ...
    def __init__(self, max_bins: int = ...) -> None: ...
    def update(self, x: Any): ...
    def iter_cdf(self, X: Any, verbose: bool = ...) -> None: ...
    def cdf(self, x: Any): ...
    def __add__(self, other: Any): ...
