from river import base
from typing import Any

def extract_relevant(model: base.Estimator) -> Any: ...
def isclassifier(model: Any): ...
def ismoclassifier(model: Any): ...
def isregressor(model: Any): ...
def ismoregressor(model: Any): ...
def isdriftdetector(model: Any): ...
