from typing import Any

def sherman_morrison(A_inv: dict, u: dict, v: dict) -> dict: ...
def dotvecmat(x: Any, A: Any): ...
def matmul2d(A: Any, B: Any): ...
def outer(u: dict, v: dict) -> dict: ...
def minkowski_distance(a: dict, b: dict, p: int) -> Any: ...
def softmax(y_pred: dict) -> Any: ...
def prod(iterable: Any): ...
def dot(x: dict, y: dict) -> Any: ...
def chain_dot(*xs: Any): ...
def sigmoid(x: float) -> Any: ...
def clamp(x: float, minimum: Any=..., maximum: Any=...) -> Any: ...
def norm(x: dict, order: Any=...) -> Any: ...
def sign(x: float) -> Any: ...
def argmax(lst: list) -> Any: ...
