import typing
from typing import Any

def print_table(headers: typing.List[str], columns: typing.List[typing.List[str]], order: typing.List[int]=...) -> Any: ...
def humanize_bytes(n_bytes: int) -> Any: ...
