from typing import Any, Optional

def get_dimensions(X: Any) -> tuple: ...
def normalize_values_in_dict(dictionary: Any, factor: Optional[Any] = ..., inplace: bool = ..., raise_error: bool = ...): ...
def get_max_value_key(dictionary: Any): ...
def calculate_object_size(obj: Any, unit: Any=...) -> int: ...
def is_scalar_nan(x: Any) -> bool: ...
def add_dict_values(dict_a: dict, dict_b: dict, inplace: Any=...) -> dict: ...
def add_delay_to_timestamps(timestamps: Any, delay: Any): ...
def check_random_state(seed: Any): ...
def round_sig_fig(x: Any, significant_digits: Any=...) -> float: ...
