import collections
from typing import Any

class Skyline(collections.UserList):
    minimize: Any = ...
    maximize: Any = ...
    def __init__(self, minimize: list=..., maximize: list=...) -> None: ...
    def update(self, x: Any): ...
