import collections
from typing import Any

class Window:
    values: Any = ...
    def __init__(self, size: int) -> None: ...
    @property
    def size(self): ...
    def __len__(self): ...
    def __getitem__(self, idx: Any): ...
    def __setitem__(self, idx: Any, val: Any): ...
    def extend(self, values: Any): ...
    def append(self, x: Any): ...
    def popleft(self): ...

class SortedWindow(collections.UserList):
    unsorted_window: Any = ...
    def __init__(self, size: int) -> None: ...
    @property
    def size(self): ...
    def append(self, x: Any): ...
