from river import base
from typing import Any

class PredClipper(base.Regressor, base.WrapperMixin):
    regressor: Any = ...
    y_min: Any = ...
    y_max: Any = ...
    def __init__(self, regressor: base.Regressor, y_min: float, y_max: float) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
