from river import base
from typing import Any

class TransformedTargetRegressor(base.Regressor, base.WrapperMixin):
    regressor: Any = ...
    func: Any = ...
    inverse_func: Any = ...
    def __init__(self, regressor: base.Regressor, func: callable, inverse_func: callable) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...

class BoxCoxRegressor(TransformedTargetRegressor):
    def __init__(self, regressor: base.Regressor, power: Any=...): ...
