from river import base
from typing import Any

class ALMAClassifier(base.Classifier):
    p: Any = ...
    alpha: Any = ...
    B: Any = ...
    C: Any = ...
    w: Any = ...
    k: int = ...
    def __init__(self, p: int = ..., alpha: float = ..., B: Any = ..., C: Any = ...) -> None: ...
    def predict_proba_one(self, x: Any): ...
    def learn_one(self, x: Any, y: Any): ...
