from river import base
from typing import Any

class BasePA:
    C: Any = ...
    mode: Any = ...
    calc_tau: Any = ...
    learn_intercept: Any = ...
    weights: Any = ...
    intercept: float = ...
    def __init__(self, C: Any, mode: Any, learn_intercept: Any) -> None: ...

class PARegressor(BasePA, base.Regressor):
    eps: Any = ...
    loss: Any = ...
    def __init__(self, C: float = ..., mode: int = ..., eps: float = ..., learn_intercept: bool = ...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...

class PAClassifier(BasePA, base.Classifier):
    loss: Any = ...
    def __init__(self, C: float = ..., mode: int = ..., learn_intercept: bool = ...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...
