from river import base, optim
from typing import Any

class SoftmaxRegression(base.Classifier):
    optimizers: Any = ...
    loss: Any = ...
    l2: Any = ...
    weights: Any = ...
    def __init__(self, optimizer: optim.Optimizer=..., loss: optim.losses.MultiClassLoss=..., l2: Any=...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...
