from . import base as base, pearson as pearson
from typing import Any

class AutoCorr(base.Univariate):
    window: Any = ...
    lag: Any = ...
    pearson: Any = ...
    def __init__(self, lag: int) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...
