from . import base as base
from typing import Any, Optional

class Count(base.Univariate):
    n: int = ...
    def __init__(self) -> None: ...
    def update(self, x: Optional[Any] = ...): ...
    def get(self): ...
