from . import base as base
from typing import Any

class Entropy(base.Univariate):
    alpha: Any = ...
    eps: Any = ...
    entropy: int = ...
    n: int = ...
    counter: Any = ...
    def __init__(self, alpha: int = ..., eps: float = ...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...
