from . import base as base
from typing import Any

class EWMean(base.Univariate):
    alpha: Any = ...
    mean: int = ...
    def __init__(self, alpha: float = ...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...
