from . import base as base, ewmean as ewmean
from typing import Any

class EWVar(base.Univariate):
    alpha: Any = ...
    mean: Any = ...
    sq_mean: Any = ...
    def __init__(self, alpha: float = ...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...
