import abc
from . import base as base, quantile as quantile
from .. import utils as utils
from typing import Any

class IQR(base.Univariate):
    q_inf: Any = ...
    q_sup: Any = ...
    quantile_inf: Any = ...
    quantile_sup: Any = ...
    def __init__(self, q_inf: float = ..., q_sup: float = ...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingIQR(base.RollingUnivariate, utils.SortedWindow, metaclass=abc.ABCMeta):
    q_inf: Any = ...
    q_sup: Any = ...
    quantile_inf: Any = ...
    quantile_sup: Any = ...
    def __init__(self, window_size: int, q_inf: Any=..., q_sup: Any=...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...
