from river import stats as stats
from typing import Any

class Link(stats.Univariate):
    left: Any = ...
    right: Any = ...
    def __init__(self, left: stats.Univariate, right: stats.Univariate) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...
    @property
    def name(self): ...
