from . import base as base
from river import utils as utils
from typing import Any

class Max(base.Univariate):
    max: Any = ...
    def __init__(self) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingMax(base.RollingUnivariate, utils.SortedWindow):
    def __init__(self, window_size: int) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any): ...
    def get(self): ...

class AbsMax(base.Univariate):
    abs_max: float = ...
    def __init__(self) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingAbsMax(base.RollingUnivariate, utils.SortedWindow):
    def __init__(self, window_size: int) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any): ...
    def get(self): ...
