from . import base as base
from river import utils as utils
from typing import Any

class Min(base.Univariate):
    min: Any = ...
    def __init__(self) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingMin(base.RollingUnivariate, utils.SortedWindow):
    def __init__(self, window_size: int) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any): ...
    def get(self): ...
