from . import base
from river import utils
from typing import Any

class Mode(base.Univariate):
    k: Any = ...
    counts: Any = ...
    def __init__(self, k: int = ...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingMode(base.RollingUnivariate, utils.Window):
    counts: Any = ...
    def __init__(self, window_size: int) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any): ...
    def get(self): ...
