from . import base as base, count as count
from typing import Any

class CentralMoments(base.Univariate):
    count: Any = ...
    delta: int = ...
    sum_delta: int = ...
    M1: int = ...
    M2: int = ...
    M3: int = ...
    M4: int = ...
    def __init__(self) -> None: ...
