from . import base as base
from typing import Any

class NUnique(base.Univariate):
    P32: Any = ...
    error_rate: Any = ...
    seed: Any = ...
    n_bits: Any = ...
    n_buckets: Any = ...
    buckets: Any = ...
    def __init__(self, error_rate: Any=..., seed: int=...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...
