from . import base as base, cov as cov, var as var
from typing import Any

class PearsonCorr(base.Bivariate):
    var_x: Any = ...
    var_y: Any = ...
    cov_xy: Any = ...
    def __init__(self, ddof: int = ...) -> None: ...
    @property
    def ddof(self): ...
    def update(self, x: Any, y: Any): ...
    def get(self): ...

class RollingPearsonCorr(base.Bivariate):
    var_x: Any = ...
    var_y: Any = ...
    cov_xy: Any = ...
    def __init__(self, window_size: Any, ddof: int = ...) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any, y: Any): ...
    def get(self): ...
