from . import base as base, maximum as maximum, minimum as minimum
from typing import Any

class PeakToPeak(base.Univariate):
    max: Any = ...
    min: Any = ...
    def __init__(self) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingPeakToPeak(base.RollingUnivariate):
    max: Any = ...
    min: Any = ...
    def __init__(self, window_size: int) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any): ...
    def get(self): ...
