from . import base as base
from river import utils as utils
from typing import Any

class Quantile(base.Univariate):
    q: Any = ...
    desired_marker_position: Any = ...
    marker_position: Any = ...
    position: Any = ...
    heights: Any = ...
    heights_sorted: bool = ...
    def __init__(self, q: float = ...) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingQuantile(base.RollingUnivariate, utils.SortedWindow):
    q: Any = ...
    idx: Any = ...
    def __init__(self, q: Any, window_size: Any) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any): ...
    def get(self): ...
