from river import stats as stats
from typing import Any, Optional

class Shift(stats.Univariate):
    amount: Any = ...
    fill_value: Any = ...
    buffer: Any = ...
    def __init__(self, amount: int = ..., fill_value: Optional[Any] = ...) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...
    @property
    def name(self): ...
