from . import moments as moments
from typing import Any

class Skew(moments.CentralMoments):
    bias: Any = ...
    def __init__(self, bias: bool = ...) -> None: ...
    @property
    def name(self): ...
    def update(self, x: Any): ...
    def get(self): ...
