from . import base as base
from .. import utils as utils
from typing import Any

class Sum(base.Univariate):
    sum: float = ...
    def __init__(self) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...

class RollingSum(base.RollingUnivariate, utils.Window):
    sum: int = ...
    def __init__(self, window_size: int) -> None: ...
    @property
    def window_size(self): ...
    def update(self, x: Any): ...
    def get(self): ...
