from .instance_conditional_test import InstanceConditionalTest as InstanceConditionalTest
from typing import Any

class NominalAttributeBinaryTest(InstanceConditionalTest):
    def __init__(self, att_idx: Any, att_value: Any) -> None: ...
    def branch_for_instance(self, x: Any): ...
    @staticmethod
    def max_branches(): ...
    def describe_condition_for_branch(self, branch: Any, shorten: bool = ...): ...
    def attrs_test_depends_on(self): ...
