from .instance_conditional_test import InstanceConditionalTest as InstanceConditionalTest
from river.utils.skmultiflow_utils import round_sig_fig as round_sig_fig
from typing import Any

class NumericAttributeBinaryTest(InstanceConditionalTest):
    def __init__(self, att_idx: Any, att_value: Any, equal_passes_test: Any) -> None: ...
    def branch_for_instance(self, x: Any): ...
    @staticmethod
    def max_branches(): ...
    def describe_condition_for_branch(self, branch: Any, shorten: bool = ...): ...
    def attrs_test_depends_on(self): ...
    @property
    def split_value(self): ...
