from . import base
from typing import Any

class Gaussian(base.ContinuousDistribution):
    def __init__(self) -> None: ...
    @property
    def n_samples(self): ...
    @property
    def mu(self): ...
    @property
    def sigma(self): ...
    @property
    def mode(self): ...
    def update(self, x: Any, w: float = ...): ...
    def pdf(self, x: Any): ...
    def cdf(self, x: Any): ...
