import typing
from . import base
from typing import Any

class Multinomial(base.DiscreteDistribution):
    counts: Any = ...
    def __init__(self, events: typing.Union[dict, list]=...) -> None: ...
    @property
    def n_samples(self): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    @property
    def mode(self): ...
    def update(self, x: Any): ...
    def pmf(self, x: Any): ...
