from . import base

class Hamming(base.MultiOutputClassificationMetric):
    @property
    def bigger_is_better(self): ...
    @property
    def requires_labels(self): ...
    def get(self): ...

class HammingLoss(base.MultiOutputClassificationMetric):
    @property
    def bigger_is_better(self): ...
    @property
    def requires_labels(self): ...
    def get(self): ...
