from . import base
from typing import Any

class RegressionMultiOutput(base.MultiOutputRegressionMetric, base.WrapperMetric):
    def __init__(self, metric: base.RegressionMetric) -> None: ...
    @property
    def metric(self): ...
    def update(self, y_true: Any, y_pred: Any, sample_weight: float = ...): ...
    def revert(self, y_true: Any, y_pred: Any, sample_weight: float = ...): ...
    def get(self): ...
