from river import metrics

class Precision(metrics.BinaryMetric):
    def get(self): ...

class MacroPrecision(metrics.MultiClassMetric):
    def get(self): ...

class MicroPrecision(metrics.MultiClassMetric):
    def get(self): ...

class WeightedPrecision(metrics.MultiClassMetric):
    def get(self): ...

class ExamplePrecision(metrics.MultiOutputClassificationMetric):
    @property
    def bigger_is_better(self): ...
    @property
    def requires_labels(self): ...
    def get(self): ...
