from . import base
from typing import Any, Optional

class R2(base.RegressionMetric):
    sample_correction: Any = ...
    def __init__(self) -> None: ...
    @property
    def bigger_is_better(self): ...
    def update(self, y_true: Any, y_pred: Any, sample_weight: float = ...): ...
    def revert(self, y_true: Any, y_pred: Any, sample_weight: Any, correction: Optional[Any] = ...): ...
    def get(self): ...
