from river import metrics

class Recall(metrics.BinaryMetric):
    def get(self): ...

class MacroRecall(metrics.MultiClassMetric):
    def get(self): ...

class MicroRecall(metrics.MicroPrecision): ...

class WeightedRecall(metrics.MultiClassMetric):
    def get(self): ...

class ExampleRecall(metrics.MultiOutputClassificationMetric):
    @property
    def bigger_is_better(self): ...
    @property
    def requires_labels(self): ...
    def get(self): ...
