from . import accuracy as accuracy, base as base, fbeta as fbeta, precision as precision, recall as recall
from .. import utils as utils
from typing import Any, Optional

class ClassificationReport(base.MultiClassMetric):
    decimals: Any = ...
    def __init__(self, decimals: int = ..., cm: Optional[Any] = ...) -> None: ...
    def get(self) -> None: ...
    @staticmethod
    def strip_trailing_zeroes(s: str) -> str: ...
