from . import base
from typing import Any

class ROCAUC(base.BinaryMetric):
    n_thresholds: Any = ...
    pos_val: Any = ...
    thresholds: Any = ...
    cms: Any = ...
    def __init__(self, n_thresholds: int = ..., pos_val: bool = ...) -> None: ...
    def update(self, y_true: Any, y_pred: Any, sample_weight: float = ...): ...
    def revert(self, y_true: Any, y_pred: Any, sample_weight: float = ...): ...
    @property
    def requires_labels(self): ...
    def get(self): ...
