from . import base
from .. import utils
from typing import Any

class Rolling(base.WrapperMetric, utils.Window):
    window_size: Any = ...
    def __init__(self, metric: base.Metric, window_size: int) -> None: ...
    @property
    def metric(self): ...
    def update(self, y_true: Any, y_pred: Any, sample_weight: float = ...): ...
    def revert(self, y_true: Any, y_pred: Any, sample_weight: float = ...): ...
