import datetime as dt
from . import base
from typing import Any

class TimeRolling(base.WrapperMetric):
    period: Any = ...
    def __init__(self, metric: base.Metric, period: dt.timedelta) -> None: ...
    @property
    def metric(self): ...
    def update(self, y_true: Any, y_pred: Any, t: Any): ...
    def revert(self, y_true: Any, y_pred: Any) -> None: ...
