from .base_split_criterion import SplitCriterion as SplitCriterion
from typing import Any

class HellingerDistanceCriterion(SplitCriterion):
    min_branch_frac_option: Any = ...
    lowest_entropy: Any = ...
    best_idx: int = ...
    def __init__(self, min_branch_frac_option: float = ...) -> None: ...
    def merit_of_split(self, pre_split_dist: Any, post_split_dist: Any): ...
    @staticmethod
    def compute_hellinger(dist: Any): ...
    @staticmethod
    def range_of_merit(pre_split_dist: Any): ...
    @staticmethod
    def num_subsets_greater_than_frac(distributions: Any, min_frac: Any): ...
