from .variance_reduction_split_criterion import VarianceReductionSplitCriterion as VarianceReductionSplitCriterion
from typing import Any

class IntraClusterVarianceReductionSplitCriterion(VarianceReductionSplitCriterion):
    def __init__(self, min_samples_split: int=...) -> None: ...
    def merit_of_split(self, pre_split_dist: Any, post_split_dist: Any): ...
    @staticmethod
    def compute_var(dist: Any): ...
