from .base_split_criterion import SplitCriterion as SplitCriterion
from typing import Any

class VarianceReductionSplitCriterion(SplitCriterion):
    min_samples_split: Any = ...
    def __init__(self, min_samples_split: int=...) -> None: ...
    def merit_of_split(self, pre_split_dist: Any, post_split_dist: Any): ...
    @staticmethod
    def compute_var(dist: Any): ...
    @staticmethod
    def range_of_merit(pre_split_dist: Any): ...
