import typing
from river import base
from typing import Any

class FuncTransformer(base.Transformer):
    func: Any = ...
    def __init__(self, func: typing.Callable[[dict], dict]) -> None: ...
    def transform_one(self, x: Any): ...
