import typing
from river import base
from typing import Any

class Grouper(base.Transformer):
    transformer: Any = ...
    by: Any = ...
    transformers: Any = ...
    def __init__(self, transformer: base.Transformer, by: typing.Union[base.typing.FeatureName, typing.List[base.typing.FeatureName]]) -> None: ...
    def learn_one(self, x: Any): ...
    def transform_one(self, x: Any): ...
