from .. import base
from typing import Any, Optional

class Renamer(base.Transformer):
    prefix: Any = ...
    suffix: Any = ...
    def __init__(self, prefix: Optional[Any] = ..., suffix: Optional[Any] = ...) -> None: ...
    def transform_one(self, x: Any): ...
