from river import base
from typing import Any, Optional

class TransformerUnion(base.Transformer):
    transformers: Any = ...
    def __init__(self, *transformers: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __len__(self): ...
    def __add__(self, other: Any): ...
    def learn_one(self, x: Any, y: Optional[Any] = ...): ...
    def transform_one(self, x: Any): ...
