from river import base as base, stats as stats
from typing import Any

class Detrender(base.Regressor, base.WrapperMixin):
    regressor: Any = ...
    mean: Any = ...
    def __init__(self, regressor: base.Regressor, window_size: int=...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...

class GroupDetrender(base.Regressor, base.WrapperMixin):
    regressor: Any = ...
    by: Any = ...
    means: Any = ...
    def __init__(self, regressor: base.Regressor, by: str, window_size: int=...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
