from river import base
from typing import Any

class OutputCodeClassifier(base.WrapperMixin, base.Classifier):
    classifier: Any = ...
    code_size: Any = ...
    seed: Any = ...
    classifiers: Any = ...
    code_book: Any = ...
    def __init__(self, classifier: base.Classifier, code_size: int, seed: int=...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
