from river import base
from typing import Any

class OneVsOneClassifier(base.WrapperMixin, base.Classifier):
    classifier: Any = ...
    classifiers: Any = ...
    classes: Any = ...
    def __init__(self, classifier: Any) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
