from river import base
from typing import Any

class OneVsRestClassifier(base.WrapperMixin, base.Classifier):
    classifier: Any = ...
    classifiers: Any = ...
    def __init__(self, classifier: base.Classifier) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...
    def learn_many(self, X: Any, y: Any, **params: Any): ...
    def predict_proba_many(self, X: Any): ...
    def predict_many(self, X: Any): ...
