from river import base as base, stats as stats
from typing import Any

class SelectKBest(base.SupervisedTransformer):
    k: Any = ...
    similarity: Any = ...
    similarities: Any = ...
    leaderboard: Any = ...
    def __init__(self, similarity: stats.Bivariate, k: Any=...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def transform_one(self, x: Any): ...
