from river import base
from typing import Any

class PoissonInclusion(base.Transformer):
    p: Any = ...
    seed: Any = ...
    rng: Any = ...
    included: Any = ...
    def __init__(self, p: float, seed: int=...) -> None: ...
    def transform_one(self, x: Any): ...
