from river import base as base, stats as stats
from typing import Any

class VarianceThreshold(base.Transformer):
    threshold: Any = ...
    min_samples: Any = ...
    variances: Any = ...
    def __init__(self, threshold: int = ..., min_samples: int = ...) -> None: ...
    def learn_one(self, x: Any): ...
    def check_feature(self, feature: Any): ...
    def transform_one(self, x: Any): ...
