import typing
from river import base, optim
from typing import Any

class EWARegressor(base.EnsembleMixin, base.Regressor):
    loss: Any = ...
    learning_rate: Any = ...
    weights: Any = ...
    def __init__(self, regressors: typing.List[base.Regressor], loss: optim.losses.RegressionLoss=..., learning_rate: Any=...) -> None: ...
    @property
    def regressors(self): ...
    def learn_predict_one(self, x: Any, y: Any): ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
