from river import base, metrics
from typing import Any

class SuccessiveHalving:
    models: Any = ...
    metric: Any = ...
    budget: Any = ...
    eta: Any = ...
    verbose: Any = ...
    print_kwargs: Any = ...
    def __init__(self, models: Any, metric: metrics.Metric, budget: int, eta: Any=..., verbose: Any=..., **print_kwargs: Any): ...
    @property
    def best_model(self): ...
    def learn_one(self, x: Any, y: Any): ...

class SuccessiveHalvingRegressor(SuccessiveHalving, base.Regressor):
    def predict_one(self, x: Any): ...

class SuccessiveHalvingClassifier(SuccessiveHalving, base.Classifier):
    def predict_proba_one(self, x: Any): ...
