import typing
from river import base
from typing import Any

class StackingClassifier(base.EnsembleMixin, base.Classifier):
    meta_classifier: Any = ...
    include_features: Any = ...
    def __init__(self, classifiers: typing.List[base.Classifier], meta_classifier: base.Classifier, include_features: Any=...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...
