from river import base
from typing import Any

class AdaBoostClassifier(base.WrapperMixin, base.EnsembleMixin, base.Classifier):
    n_models: Any = ...
    model: Any = ...
    seed: Any = ...
    wrong_weight: Any = ...
    correct_weight: Any = ...
    def __init__(self, model: base.Classifier, n_models: Any=..., seed: int=...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...
