from river import base, stats
from typing import Any

class NoChangeClassifier(base.Classifier):
    last_class: Any = ...
    classes: Any = ...
    def __init__(self) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
    def predict_proba_one(self, x: Any): ...

class PriorClassifier(base.Classifier):
    counts: Any = ...
    n: int = ...
    def __init__(self) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...

class StatisticRegressor(base.Regressor):
    statistic: Any = ...
    def __init__(self, statistic: stats.Univariate) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
