import abc
import pandas as pd
from river import base as base
from typing import Any

class BaseNB(base.Classifier, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def joint_log_likelihood(self, x: dict) -> float: ...
    @abc.abstractmethod
    def joint_log_likelihood_many(self, X: pd.DataFrame) -> pd.DataFrame: ...
    def predict_proba_one(self, x: Any): ...
    def predict_proba_many(self, X: pd.DataFrame) -> pd.DataFrame: ...

def from_dict(data: dict) -> pd.DataFrame: ...
def one_hot_encode(y: pd.Series) -> pd.DataFrame: ...
