import pandas as pd
from . import base
from typing import Any

class BernoulliNB(base.BaseNB):
    alpha: Any = ...
    true_threshold: Any = ...
    class_counts: Any = ...
    feature_counts: Any = ...
    def __init__(self, alpha: float = ..., true_threshold: float = ...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def p_feature_given_class(self, f: str, c: str) -> float: ...
    def p_class(self, c: str) -> float: ...
    def p_class_many(self) -> pd.DataFrame: ...
    def joint_log_likelihood(self, x: Any): ...
    def learn_many(self, X: pd.DataFrame, y: pd.Series) -> Any: ...
    def joint_log_likelihood_many(self, X: pd.DataFrame) -> pd.DataFrame: ...
