import pandas as pd
from . import base
from typing import Any

class ComplementNB(base.BaseNB):
    alpha: Any = ...
    class_counts: Any = ...
    feature_counts: Any = ...
    feature_totals: Any = ...
    class_totals: Any = ...
    def __init__(self, alpha: float = ...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def p_class(self, c: Any): ...
    def p_class_many(self) -> pd.DataFrame: ...
    def joint_log_likelihood(self, x: Any): ...
    def learn_many(self, X: pd.DataFrame, y: pd.Series) -> Any: ...
    def joint_log_likelihood_many(self, X: pd.DataFrame) -> pd.DataFrame: ...
