import pandas as pd
from . import base
from typing import Any

class GaussianNB(base.BaseNB):
    class_counts: Any = ...
    gaussians: Any = ...
    def __init__(self) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def p_class(self, c: Any): ...
    def joint_log_likelihood(self, x: Any): ...
    def joint_log_likelihood_many(self, X: pd.DataFrame) -> Any: ...
