import pandas as pd
from . import base
from typing import Any

class MultinomialNB(base.BaseNB):
    alpha: Any = ...
    class_counts: Any = ...
    feature_counts: Any = ...
    class_totals: Any = ...
    def __init__(self, alpha: float = ...) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    @property
    def classes_(self): ...
    @property
    def n_terms(self): ...
    def p_feature_given_class(self, f: Any, c: Any): ...
    def p_class(self, c: Any) -> float: ...
    def p_class_many(self) -> pd.DataFrame: ...
    def joint_log_likelihood(self, x: Any): ...
    def learn_many(self, X: pd.DataFrame, y: pd.Series) -> Any: ...
    def joint_log_likelihood_many(self, X: pd.DataFrame) -> pd.DataFrame: ...
