from river import utils as utils
from typing import Any, Optional

class Cache:
    directory: Any = ...
    keys: Any = ...
    def __init__(self, directory: Optional[Any] = ...) -> None: ...
    def __call__(self, stream: Any, key: Optional[Any] = ...) -> None: ...
    def __getitem__(self, key: Any) -> None: ...
    def clear(self, key: str) -> Any: ...
    def clear_all(self) -> None: ...
