import csv
import typing
from .. import base
from typing import Any

class DictReader(csv.DictReader):
    fraction: Any = ...
    rng: Any = ...
    def __init__(self, fraction: Any, rng: Any, *args: Any, **kwargs: Any) -> None: ...
    def __next__(self): ...

def iter_csv(filepath_or_buffer: Any, target: typing.Union[str, typing.List[str]]=..., converters: dict=..., parse_dates: dict=..., drop: typing.List[str]=..., fraction: Any=..., compression: Any=..., seed: int=..., field_size_limit: int=..., **kwargs: Any) -> base.typing.Stream: ...
