from .base_neighbors import BaseNeighbors as BaseNeighbors
from river import base as base
from river.utils import dict2numpy as dict2numpy
from river.utils.math import softmax as softmax
from typing import Any

class KNNClassifier(BaseNeighbors, base.Classifier):
    weighted: Any = ...
    classes_: Any = ...
    kwargs: Any = ...
    def __init__(self, n_neighbors: int=..., window_size: int=..., leaf_size: int=..., p: float=..., weighted: bool=..., **kwargs: Any) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...
