from .base_neighbors import BaseNeighbors as BaseNeighbors
from river import base as base
from river.utils import dict2numpy as dict2numpy
from typing import Any

class KNNRegressor(BaseNeighbors, base.Regressor):
    aggregation_method: Any = ...
    kwargs: Any = ...
    def __init__(self, n_neighbors: int=..., window_size: int=..., leaf_size: int=..., p: float=..., aggregation_method: str=..., **kwargs: Any) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def predict_one(self, x: Any): ...
