def get1ToNDistances(*args, **kwargs) -> Any: ...
def getLinearWeightedLabels(*args, **kwargs) -> Any: ...
def getNToNDistances(*args, **kwargs) -> Any: ...
def mostCommon(*args, **kwargs) -> Any: ...
def nArgMin(*args, **kwargs) -> Any: ...
