import torch
from .. import base
from typing import Any

class PyTorch2RiverBase:
    net: Any = ...
    loss_fn: Any = ...
    optimizer: Any = ...
    batch_size: Any = ...
    x_tensor: Any = ...
    y_tensor: Any = ...
    def __init__(self, net: Any, loss_fn: Any, optimizer: Any, batch_size: Any, x_tensor: Any, y_tensor: Any) -> None: ...
    def learn_one(self, x: Any, y: Any): ...

class PyTorch2RiverRegressor(PyTorch2RiverBase, base.Regressor):
    def __init__(self, net: torch.nn.Sequential, loss_fn: torch.nn.modules.loss._Loss, optimizer: torch.optim.Optimizer, batch_size: Any=...) -> None: ...
    def predict_one(self, x: Any): ...
