from river import base
from sklearn import base as sklearn_base
from typing import Any

def convert_sklearn_to_river(estimator: sklearn_base.BaseEstimator, classes: list=...) -> Any: ...

class SKL2RiverBase:
    estimator: Any = ...
    def __init__(self, estimator: sklearn_base.BaseEstimator) -> None: ...

class SKL2RiverRegressor(SKL2RiverBase, base.Regressor):
    def learn_one(self, x: Any, y: Any): ...
    def learn_many(self, X: Any, y: Any): ...
    def predict_one(self, x: Any): ...
    def predict_many(self, X: Any): ...

class SKL2RiverClassifier(SKL2RiverBase, base.Classifier):
    classes: Any = ...
    def __init__(self, estimator: sklearn_base.ClassifierMixin, classes: list) -> None: ...
    def learn_one(self, x: Any, y: Any): ...
    def learn_many(self, X: Any, y: Any): ...
    def predict_proba_one(self, x: Any): ...
    def predict_proba_many(self, X: Any): ...
    def predict_one(self, x: Any): ...
    def predict_many(self, X: Any): ...
