import typing
from river import base
from typing import Any

class HalfSpaceTrees(base.AnomalyDetector):
    n_trees: Any = ...
    window_size: Any = ...
    height: Any = ...
    limits: Any = ...
    seed: Any = ...
    rng: Any = ...
    trees: Any = ...
    counter: int = ...
    def __init__(self, n_trees: Any=..., height: Any=..., window_size: Any=..., limits: typing.Dict[base.typing.FeatureName, typing.Tuple[float, float]]=..., seed: int=...) -> None: ...
    @property
    def size_limit(self): ...
    def learn_one(self, x: Any): ...
    def score_one(self, x: Any): ...
