from river import base
from typing import Any

class FeatureHasher(base.Transformer):
    n_features: Any = ...
    seed: Any = ...
    def __init__(self, n_features: Any=..., seed: int=...) -> None: ...
    def transform_one(self, x: Any): ...
