import typing
from river import base, stats
from typing import Any

class PreviousImputer(base.Transformer):
    def __init__(self) -> None: ...
    def learn_one(self, x: Any): ...
    def transform_one(self, x: Any): ...

class StatImputer(base.Transformer):
    stats: Any = ...
    def __init__(self, *imputers: Any) -> None: ...
    def learn_one(self, x: Any): ...
    def transform_one(self, x: Any): ...

class Constant(stats.Univariate):
    value: Any = ...
    def __init__(self, value: typing.Any) -> None: ...
    def update(self, x: Any): ...
    def get(self): ...
    @property
    def name(self): ...
