from river import base
from typing import Any, Optional

class OneHotEncoder(base.Transformer):
    sparse: Any = ...
    values: Any = ...
    def __init__(self, sparse: bool = ...) -> None: ...
    def learn_one(self, x: Any): ...
    def transform_one(self, x: Any, y: Optional[Any] = ...): ...
